### PR TITLE
Update CI branch from master to trunk

### PR DESCRIPTION
**Pull request by oguzkocer**
We have renamed the default branch from `master` to `trunk`. This PR updates the CI config files to reflect that change.

### CODE REVIEW

**Review by AliSoftware — APPROVED** [review]
Changes look good. CI is failing though (apparently unable to find the appropriate NDK in the CI image).
Not sure if we want to fix it while at it (to avoid merging a failing state into `trunk`) by updating the image used or making the workflow install the NDK beforehand?

**Comment by oguzkocer** [comment]
@AliSoftware I don't think the issue is that NDK is not available in the CI. As far as I know, the Android Gradle Plugin should have everything necessary. The base repository runs the same Github action without any issues, so maybe all that's needed is to merge the base changes. Having said that, I took a quick look at the differences and I don't see what would actually fix this issue.

Unfortunately I don't know how to fix the issue without spending too much time on this and I don't want to do that as part of a branch rename. I've a lot of higher priority tasks to get to. Sorry about that!

@hypest @mchowning I don't know if you update the forks with the base repositories. If you do, it might be worth bringing in those changes to see if that fixes the issue. I'll leave the decision for merging this PR to you as well.

**Comment by hypest** [comment]
Thanks for the ping @oguzkocer!

It's totally safe to update from upstream here, please feel free to.

Just to add context, the version we use in gutenberg-mobile is tracked by [this kept-open PR](https://github.com/wordpress-mobile/react-native-safe-area-context/pull/3), which we only update when needed so, it's safe to update the default branch, no problem.

Let me know if that unblocks the effort here, thanks!

**Comment by oguzkocer** [comment]
@hypest Thanks for your input. I'll merge this PR and create a new one to update from upstream. I am not sure if that'll fix the CI issue, but it's worth a try 🤷

**Comment by oguzkocer** [comment]
I've created a PR for updating from upstream https://github.com/wordpress-mobile/react-native-safe-area-context/pull/8 however that hasn't resolved the issue in the Android build. I checked upstream and the last android build (which was successful) from the `main` branch happened 4 months ago. A `v2` seems to be on its way very soon and it's successfully building the Android example app in CI.

Since the only difference we have with upstream is the default branch name (from this PR), I think the CI issue is not worth further investigation. The upstream's `v2` branch has updated Gradle to `7.3`, I imagine that might resolve the issue but I am still not familiar enough with the `react-native` Android project setup to be confident.

**Pull request merged**
